version: '3.8'

services:
  playlist_downloader:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: youtube-playlist-downloader
    environment:
      - PLAYLIST_URL=${PLAYLIST_URL}
    volumes:
      - ../downloads:/downloads              # Shared downloads directory
      - ../script:/app/script                # Mount ../script as /app/script
    working_dir: /app/playlist_downloader
    command: sh -c "python download_playlist.py \"$PLAYLIST_URL\""
    stdin_open: true
    tty: true
    restart: "no"
