version: '3.8'

services:
  playlist_downloader:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: youtube-playlist-downloader
    environment:
      - PLAYLIST_URL=${PLAYLIST_URL:?Variable PLAYLIST_URL is required}
      - ENABLE_TRANSCRIPTION=${ENABLE_TRANSCRIPTION:?Variable ENABLE_TRANSCRIPTION is required}
    volumes:
      - ../downloads:/downloads              # Shared downloads directory
      - ../script:/app/script                # Mount ../script as /app/script
      - ../playlist_downloader:/app/playlist_downloader  # Use absolute path for playlist_downloader
    working_dir: /app/playlist_downloader
    command: sh -c "ls -al /app/playlist_downloader && sh ./playlist.sh"
    stdin_open: true
    tty: true
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 1g  # Adjust memory as needed
