version: '3.8'

services:
  video_downloader:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: youtube-video-downloader
    environment:
      - VIDEO_URL=${VIDEO_URL}
    volumes:
      - ../downloads:/downloads              # Shared downloads directory
      - ../script:/app/script                # Mount ../script as /app/script
    working_dir: /app/video_downloader
    command: sh -c "python download_video.py \"$VIDEO_URL\""
    stdin_open: true
    tty: true
    restart: "no"
