version: '3.8'

services:
  video_downloader:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        UUID: ${UUID:?UUID is required}  # Passes UUID from host environment
        GUID: ${GUID:?GUID is required}  # Passes GUID from host environment

    container_name: youtube-video-downloader

    # Environment variables for the application
    environment:
      - VIDEO_URL=${VIDEO_URL:?Variable VIDEO_URL is required}
      - ENABLE_TRANSCRIPTION=${ENABLE_TRANSCRIPTION:?Variable ENABLE_TRANSCRIPTION is required}

    # Mounting necessary directories securely
    volumes:
      - ../downloads:/downloads:rw             # Shared downloads directory with read-write permissions
      - ../script:/app/script:ro               # Mount ../script as /app/script in read-only mode
      - ../video_downloader:/app/video_downloader:ro  # Use absolute path for video_downloader in read-only mode

    working_dir: /app/video_downloader

    # Command to execute the main script
    command: sh -c "sh ./video.sh"

    # Capabilities
    cap_drop:
      - ALL  # Drops all Linux capabilities to enhance security

    # Restart policy and resource constraints for stability and security
    stdin_open: true
    tty: true
    restart: "no"

    deploy:
      resources:
        limits:
          memory: 3g  # Restricts container memory usage to 3GB
